name = "tienda-chica"
compatibility_date = "2024-03-15"
compatibility_flags = ["nodejs_compat"]

[vars]
API_URL = "https://tu-api.com"

[build]
command = "npm run pages:build"

[site]
bucket = ".vercel/output"

main = ".vercel/output/static/_worker.js/index.js"
